### PR TITLE
Update StormLib to commit 5ab093b7a57b8779dff06a08fac19d46c40b3329, and build StormLib as a cmake ExternalProject

### PR DESCRIPTION
**Pull request by abenedic**
This commit is to fix issue #396.  This pull request is to update StormLib to the latest commit as of today, and to fix how StormLib is built as part of the build process.  I have only tested this on macOS, but am planning on testing on Fedora 35 later.

I cloned StormLib locally, then copied all the non-hidden files and pasted them over the existing files in the StormLib directory.  I did that since there are files like `Makefile.mac` that do not exist in the upstream StormLib.  I then had to modify the existing `CMakeLists.txt` in order for the build to work since the `Makefile.mac` that was used was causing errors while building StormLib.  I decided to make it an ExternalProject since that seemed like the conventional solution.

Let me know if you need anything changed.  There is another commit attached to add .DS_store files to the .gitignore, since I accidentally committed them.

### CODE REVIEW

**Comment by abenedic** [comment]
This commit has an issue with the case on libstorm. Since macOS is case insensitive it worked there.

**Comment by abenedic** [comment]
This now builds on Fedora 35 as well, however I cannot run wargus there since I get the weird lua error still.

**Comment by timfel** [comment]
This looks good to me. Did you manage to run the extractor using this wargus build on Fedora, even if the launch failed?

**Comment by abenedic** [comment]
Yes and the extractor seemed to run fine. At least it seems to generate the same files as before.

**Comment by abenedic** [comment]
So this does build and run on macOS, just with  the GUI not really working: https://youtu.be/YC80ZD8vup8

**Pull request merged**
