### PR TITLE
Direct multiplayer script

### PR DESCRIPTION
**Pull request by timfel**
This depends on https://github.com/Wargus/stratagus/pull/157, and enables a form of what was requested in https://github.com/Wargus/wargus/issues/132.
This will start a server:
`wargus -c multiplayer -G server,race=human,map=islands.smp.gz,numplayers=2`
This will start a client:
`wargus -c multiplayer -G client,race=orc,ip=192.168.1.100`

Both games will go to the preparation room, but the game will start automatically once all connections are established, so no user interaction is required to get into the game. @mimooh, does that work for you?

### CODE REVIEW

**Comment by mimooh** [comment]
Wow! I'll soon let you know if it works. Meanwhile I'd like to donate,
as promised. Not much familar with PayPal - will it be fine if I send 10
Euro to your email?

-- 
Karol Kreński

**Comment by timfel** [comment]
Do try it first to see if it works for you :) But sure, if you want, my email address is also on paypal.

**Comment by mimooh** [comment]
Works like a charm! Thanks a lot! My comments are:

1. The calling example should be rather: 
map=./maps/islands.smp.gz
not
map=islands.smp.gz

2. Setting the player name also works, just lacks documenting, so:
multiplayer -G client,race=orc,ip=192.168.1.100,player='mimooh'
not
multiplayer -G client,race=orc,ip=192.168.1.100

**Comment by timfel** [comment]
I will look into how to select the map. I have included the optional setting of the player name in the man page: https://github.com/Wargus/wargus/blob/master/doc/wargus.6

**Pull request merged**
